name: Discord Release notifications
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord about release
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            🚀 **New release published**
            ${{ github.event.release.name }} (${{
              github.event.release.tag_name }})
            ${{ github.event.release.html_url }}
