name: Discord CI notifications
on:
  workflow_run:
    workflows: ["CI", "Tests", "Build"]
    types: [completed]

jobs:
  discord:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Send CI failure to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ⚠️ **CI ${{ github.event.workflow_run.conclusion }}**
            Workflow: ${{ github.event.workflow_run.name }}
            By: ${{ github.event.workflow_run.actor.login }}
            Run URL: ${{ github.event.workflow_run.html_url }}
