name: Discord notifications (PRs & Releases)

on:
  pull_request:
    types: [opened, reopened, closed, edited, labeled, unlabeled, synchronize]
  release:
    types: [published]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR info to Discord
        if: ${{ github.event_name == 'pull_request' }}
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            **PR ${{ github.event.action }}**
            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Base: ${{ github.event.pull_request.base.ref }} ← ${{ github.event.pull_request.base.repo.full_name }}
            Head: ${{ github.event.pull_request.head.ref }} (repo: ${{ github.event.pull_request.head.repo.full_name }})
            URL: ${{ github.event.pull_request.html_url }}

      - name: Send Release info to Discord
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            🚀 **New release published**
            Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Author: ${{ github.event.release.author.login }}
            URL: ${{ github.event.release.html_url }}
